# View Protocol documentation and information about the mod here:
# https://github.com/Noxcrew/noxesium

# If true will check the plugin's version once in a while.
checkForUpdates: true

# It true will send defaults to Noxesium Players on join.
sendDefaultsOnJoin: false

# comment out the line if you don't want to send that rule.
defaults:
  #disableAutoSpinAttack: false # since protocol 1
  #globalCanPlaceOn: [] # unsupported. since protocol 1
  #globalCanDestroy: [] # unsupported. since protocol 1
  #heldItemNameOffset: 0 # unsupported. since protocol 2
  #cameraLocked: false # since protocol 2