# View Protocol documentation and information about the mod here:
# https://github.com/Noxcrew/noxesium

# If true will check the plugin's version once in a while.
checkForUpdates: true

# It true will send defaults to Noxesium Players on join.
sendDefaultsOnJoin: false

# Comment out the line if you don't want to send that rule.
defaults:
  #disableAutoSpinAttack: false # since protocol 1
  #globalCanPlaceOn: [] # since protocol 1
  #globalCanDestroy: [] # since protocol 1
  #heldItemNameOffset: 0 # since protocol 2
  #cameraLocked: false # since protocol 2
  #enableCustomMusic: false # since protocol 3
  #disableBoatCollision: false # since protocol 4