sendDefaultsOnJoin: false
defaults:
  # comment out the line if you don't want to send that rule.
  disableAutoSpinAttack: false # since protocol 1
  #globalCanPlaceOn: [] # unsupported. since protocol 1
  #globalCanDestroy: [] # unsupported. since protocol 1
  #heldItemNameOffset: 0 # unsupported. since protocol 2
  #cameraLocked: false # unsupported. since protocol 2