# View Protocol documentation and information about the mod here:
# https://github.com/Noxcrew/noxesium

# If true will check the plugin's version once in a while.
checkForUpdates: true

# It true will send defaults to Noxesium Players on join.
sendDefaultsOnJoin: false

# Comment out the line if you don't want to send that rule.
defaults:
  #cameraLocked: false
  #disableBoatCollisions: false
  #disableDeferredChunkUpdates: false
  #disableMapUi: false
  #disableSpinAttackCollisions: false
  #disableUiOptimizations: false
  #disableVanillaMusic: false
  #enableSmootherClientTrident: false
  #heldItemNameOffset: 0
  #overrideGraphicsMode: FAST
  #riptideCoyoteTime: 0
  #showMapInUi: false

#qibDefinitions: 
#  example:
#    onEnter: 'example_qib_enter.json'
#    onLeave: 'example_qib_leave.json'
#    triggerEnterLeaveOnSwitch: false