name: NoxesiumUtils
author: SuperNeon4ik
description: Communicate with Noxesium with ease.
version: '${project.version}'
main: me.superneon4ik.noxesiumutils.NoxesiumUtils
api-version: 1.20
website: https://github.com/SuperNeon4ik/NoxesiumUtils

permissions:
  noxesiumutils.commands:
    description: Access the /noxesiumutils command.