name: NoxesiumUtils
author: SuperNeon4ik
description: Interact with Noxesium from the server.
version: '${project.version}'
main: me.superneon4ik.noxesiumutils.NoxesiumUtils
api-version: 1.19

permissions:
  noxesiumutils.commands:
    description: Access the /noxesiumutils command.